[runner]
workers = 8
wmdrun = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

[simulation]
interfaces = [
    -1.7000,
    -1.4225,
    -1.2525,
    -1.0350,
    -0.5350,
    -0.4650,
    -0.4200,
    -0.3775,
    -0.3400,
    -0.3075,
    -0.2775,
    -0.2400,
    -0.2050,
    -0.1650,
    -0.1325,
     1.7000,
]
steps = 100000
seed = 0
load_dir = "load"
load_dir1 = "load1"
shooting_moves = ["sh", "sh", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf", "wf"]
eng_sw_prob =    [0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50]
ensemble_engines = [
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ], 
]

[simulation.tis_set]
maxlength = 100000
allowmaxlength = false
zero_momentum = false
n_jumps = 1
lambda_minus_one = -2.3

[engine0]
class = "ase"
engine = "ase"
temperature = 300
input_path = "."
timestep = 1
subcycles = 1
integrator = "langevin"
langevin_fixcm = false
langevin_friction = 0.001

[engine0.calculator_settings]
module = "../potential.py"
class = "DoubleDip"

[engine1]
class = "ase"
engine = "ase"
temperature = 300
input_path = "."
timestep = 1
subcycles = 1
integrator = "langevin"
langevin_fixcm = false
langevin_friction = 0.001

[engine1.calculator_settings]
module = "../potential.py"
class = "Gaussian"

[orderparameter]
class = "Position"
index = [0,0]
periodic = false

[output]
data_dir = "./"
screen = 1
pattern = true
delete_old = true
delete_old_all = false
