[runner]
workers = 4
wmdrun = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

[simulation]
interfaces = [
    -0.7,
    -0.551,
    -0.496,
    -0.451,
    -0.405,
    -0.359,
    -0.313,
    -0.25,
    -0.168,
    0.7,
]
steps = 100000
seed = 0
load_dir = "load"
shooting_moves = [
    "sh",
    "sh",
    "wf",
    "wf",
    "wf",
    "wf",
    "wf",
    "wf",
    "wf",
    "wf",
]
eng_sw_prob = [
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
]
ensemble_engines = [
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
    [
        "engine0", "engine1"
    ],
]

[simulation.tis_set]
maxlength = 100000
allowmaxlength = false
zero_momentum = true
n_jumps = 1
interface_cap = 0.4

[engine0]
class = "ase"
engine = "ase"
temperature = 300
input_path = "."
timestep = 0.5
subcycles = 2
integrator = "velocityverlet"

[engine0.calculator_settings]
module = "../xtbcalc.py"
class = "XTBInteractions"

[engine1]
class = "ase"
engine = "ase"
temperature = 300
input_path = "."
timestep = 0.5
subcycles = 2
integrator = "velocityverlet"

[engine1.calculator_settings]
module = "../bondedcalc.py"
class = "BondedInteractions"
bonds = [
    [
        34.03214568,
        1.019,
        0,
        1,
    ],
    [
        34.03214568,
        1.019,
        0,
        2,
    ],
    [
        34.03214568,
        1.019,
        0,
        3,
    ],
]
angles = [
    [
        3.59054748,
        1.8570303241219668,
        1,
        0,
        2,
    ],
    [
        3.59054748,
        1.8570303241219668,
        1,
        0,
        3,
    ],
    [
        3.59054748,
        1.8570303241219668,
        2,
        0,
        3,
    ],
]

[orderparameter]
class = "Dihedral"
index = [
    0,
    1,
    2,
    3,
]
periodic = false

[output]
data_dir = "./"
screen = 1
pattern = true
delete_old = true
keep_maxop_trajs = true
